# Generated by Django 5.0.4 on 2024-05-01 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produt',
            new_name='Product',
        ),
    ]
